# Generated by Django 5.2 on 2025-06-10 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email_message',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email_message',
            name='TO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email_message',
            name='bcc_users',
            field=models.ManyToManyField(related_name='bcc_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email_message',
            name='cc_users',
            field=models.ManyToManyField(related_name='cc_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email_message',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communication.email_message'),
        ),
        migrations.AddField(
            model_name='childtemplatetype',
            name='parent_template_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.parenttemplatetype'),
        ),
        migrations.AddField(
            model_name='reminderemail',
            name='receivers',
            field=models.ManyToManyField(related_name='reminder_emails_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminderemail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='bcc_users',
            field=models.ManyToManyField(blank=True, related_name='scheduled_emails_bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='scheduled_emails_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='receivers',
            field=models.ManyToManyField(related_name='scheduled_emails_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminderemail',
            name='scheduled_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.scheduledemail'),
        ),
        migrations.AddField(
            model_name='template',
            name='child_template_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.childtemplatetype'),
        ),
    ]
